# Generated by Django 4.0.3 on 2022-06-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
