# Generated by Django 4.0.3 on 2022-06-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='id',
            new_name='reservation_number',
        ),
    ]
